Upgrade to debian 11
Bonus, it fixes this other error
https://github.com/badouralix/vscode-remote-try-r/runs/4122941204

    c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1